diffle_shop:
  target: dev
  outputs:
    dev:
      dbname: postgres
      host: localhost
      password: dbt_dave
      port: 5432
      schema: dev
      threads: 2
      type: postgres
      user: daveconnors
    prod:
      dbname: postgres
      host: localhost
      password: dbt_dave
      port: 5432
      schema: prod
      threads: 2
      type: postgres
      user: daveconnors
